version: '3.8'

services:
  postgres_catalogo:
    image: 'postgres:latest'
    container_name: postgres_catalogo
    environment:
      - 'POSTGRES_DB=catalogo'
      - 'POSTGRES_USER=myuser'
      - 'POSTGRES_PASSWORD=mypassword'
    ports:
      - "5433:5432"
    volumes:
      - catalogo_postgres:/var/lib/postgresql/data
volumes:
  catalogo_postgres: